#!/bin/bash
#
# Uninstall beads-compound plugin from OpenCode
#
# Usage:
#   Called by uninstall.sh -opencode [target]
#

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Default to ~/.config/opencode if no argument provided
if [ $# -eq 0 ]; then
  TARGET="$HOME/.config/opencode"
  GLOBAL_UNINSTALL=true
else
  TARGET="$1"
  GLOBAL_UNINSTALL=false
fi

# Resolve to absolute path
if [ ! -d "$TARGET" ]; then
  echo "[!] Error: Target directory does not exist: $TARGET"
  exit 1
fi

TARGET="$(cd "$TARGET" && pwd)"

echo "🗑️  beads-compound OpenCode Uninstaller"
echo ""
echo "Target: $TARGET"
if [ "$GLOBAL_UNINSTALL" = true ]; then
  echo "Type: Global uninstallation"
else
  echo "Type: Project-specific uninstallation"
fi
echo ""

# Warning
echo "⚠️  This will remove:"
echo "  - TypeScript plugin (plugins/beads-compound/)"
echo "  - All hooks (.opencode/hooks/)"
echo "  - All commands (.opencode/commands/)"
echo "  - All agents (.opencode/agents/)"
echo "  - All skills (.opencode/skills/)"
echo "  - Memory scripts (recall.sh, knowledge-db.sh)"
echo ""
echo "Note: Your knowledge.jsonl database will be preserved"
echo ""

read -p "Continue? (y/N) " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
  echo "Uninstall cancelled."
  exit 0
fi

echo ""
echo "🗑️  Removing files..."

# Remove plugin
if [ -d "$TARGET/plugins/beads-compound" ]; then
  rm -rf "$TARGET/plugins/beads-compound"
  echo "  ✓ Removed TypeScript plugin"
fi

# Remove hooks
if [ -d "$TARGET/.opencode/hooks" ]; then
  for hook in auto-recall.sh memory-capture.sh subagent-wrapup.sh; do
    if [ -f "$TARGET/.opencode/hooks/$hook" ]; then
      rm "$TARGET/.opencode/hooks/$hook"
      echo "  ✓ Removed $hook"
    fi
  done
fi

# Remove commands
if [ -d "$TARGET/.opencode/commands" ]; then
  # Remove all .md files generated by plugin
  find "$TARGET/.opencode/commands" -type f -name "*.md" -exec grep -l "Generated by beads-compound" {} \; -delete 2>/dev/null || true
  echo "  ✓ Removed commands"
fi

# Remove agents
if [ -d "$TARGET/.opencode/agents" ]; then
  for category in review research design workflow docs; do
    if [ -d "$TARGET/.opencode/agents/$category" ]; then
      find "$TARGET/.opencode/agents/$category" -type f -name "*.md" -exec grep -l "Generated by beads-compound" {} \; -delete 2>/dev/null || true
    fi
  done
  echo "  ✓ Removed agents"
fi

# Remove skills
if [ -d "$TARGET/.opencode/skills" ]; then
  # List of known plugin skills
  PLUGIN_SKILLS=(
    git-worktree brainstorming create-agent-skills agent-native-architecture
    beads-knowledge agent-browser andrew-kane-gem-writer dhh-rails-style
    dspy-ruby every-style-editor file-todos frontend-design gemini-imagegen
    rclone skill-creator
  )

  for skill in "${PLUGIN_SKILLS[@]}"; do
    if [ -d "$TARGET/.opencode/skills/$skill" ]; then
      # Verify it's a plugin skill by checking for generation marker
      if grep -q "Generated by beads-compound" "$TARGET/.opencode/skills/$skill/SKILL.md" 2>/dev/null; then
        rm -rf "$TARGET/.opencode/skills/$skill"
        echo "  ✓ Removed skill: $skill"
      fi
    fi
  done
fi

# Remove memory scripts (keep knowledge.jsonl - that's user data)
if [ -d "$TARGET/.beads/memory" ]; then
  # Remove plugin scripts only
  if [ -f "$TARGET/.beads/memory/recall.sh" ]; then
    rm "$TARGET/.beads/memory/recall.sh"
    echo "  ✓ Removed recall.sh"
  fi
  if [ -f "$TARGET/.beads/memory/knowledge-db.sh" ]; then
    rm "$TARGET/.beads/memory/knowledge-db.sh"
    echo "  ✓ Removed knowledge-db.sh"
  fi

  # Note: knowledge.jsonl and knowledge.archive.jsonl are preserved (user data)
  if [ -f "$TARGET/.beads/memory/knowledge.jsonl" ]; then
    echo "  ⊘ Kept knowledge.jsonl (user data preserved)"
  fi
fi

echo ""
echo "✅ Uninstall complete!"
echo ""

if [ "$GLOBAL_UNINSTALL" = true ]; then
  echo "Global uninstallation complete. OpenCode no longer has access to beads-compound."
else
  echo "Project-specific uninstallation complete for: $TARGET"
fi
